###### Keras

In [18]:
import numpy as np

In [19]:
from sklearn.datasets import load_iris
iris = load_iris()

In [20]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [21]:
X = iris.data
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [22]:
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

###### One Hot Endocding

In [25]:
from tensorflow.keras.utils import to_categorical

In [27]:
y = to_categorical(y)

In [28]:
y.shape

(150, 3)

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.33,
                                                    random_state=42)

###### Normalization

In [34]:
from sklearn.preprocessing import MinMaxScaler

In [35]:
scaler_object = MinMaxScaler()

In [36]:
scaler_object.fit(X_train)

MinMaxScaler()

In [38]:
scaled_X_train = scaler_object.transform(X_train)

In [39]:
scaled_X_test = scaler_object.transform(X_test)

In [41]:
scaled_X_train

array([[0.41176471, 0.40909091, 0.55357143, 0.5       ],
       [0.97058824, 0.45454545, 0.98214286, 0.83333333],
       [0.38235294, 0.45454545, 0.60714286, 0.58333333],
       [0.23529412, 0.68181818, 0.05357143, 0.04166667],
       [1.        , 0.36363636, 1.        , 0.79166667],
       [0.44117647, 0.31818182, 0.53571429, 0.375     ],
       [0.26470588, 0.63636364, 0.05357143, 0.04166667],
       [0.20588235, 0.68181818, 0.03571429, 0.08333333],
       [0.23529412, 0.81818182, 0.14285714, 0.125     ],
       [0.20588235, 0.        , 0.42857143, 0.375     ],
       [0.58823529, 0.31818182, 0.67857143, 0.70833333],
       [0.14705882, 0.63636364, 0.14285714, 0.04166667],
       [0.20588235, 0.45454545, 0.08928571, 0.04166667],
       [0.23529412, 0.59090909, 0.10714286, 0.16666667],
       [0.38235294, 0.31818182, 0.55357143, 0.5       ],
       [0.23529412, 0.63636364, 0.07142857, 0.04166667],
       [0.41176471, 0.45454545, 0.55357143, 0.45833333],
       [1.        , 0.81818182,

In [42]:
from keras.models import Sequential
from keras.layers import Dense

In [43]:
model = Sequential()
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(3,activation='softmax'))  # using 3 perceptrons to match the discriptor attributes
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [44]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [45]:
model.fit(scaled_X_train,y_train,epochs=150,verbose=2)

Epoch 1/150
4/4 - 0s - loss: 1.2059 - accuracy: 0.3800 - 307ms/epoch - 77ms/step
Epoch 2/150
4/4 - 0s - loss: 1.1918 - accuracy: 0.3900 - 5ms/epoch - 1ms/step
Epoch 3/150
4/4 - 0s - loss: 1.1798 - accuracy: 0.3800 - 5ms/epoch - 1ms/step
Epoch 4/150
4/4 - 0s - loss: 1.1678 - accuracy: 0.3800 - 5ms/epoch - 1ms/step
Epoch 5/150
4/4 - 0s - loss: 1.1561 - accuracy: 0.3900 - 5ms/epoch - 1ms/step
Epoch 6/150
4/4 - 0s - loss: 1.1462 - accuracy: 0.4100 - 4ms/epoch - 1ms/step
Epoch 7/150
4/4 - 0s - loss: 1.1358 - accuracy: 0.4200 - 4ms/epoch - 1ms/step
Epoch 8/150
4/4 - 0s - loss: 1.1271 - accuracy: 0.4200 - 5ms/epoch - 1ms/step
Epoch 9/150
4/4 - 0s - loss: 1.1184 - accuracy: 0.4300 - 6ms/epoch - 1ms/step
Epoch 10/150
4/4 - 0s - loss: 1.1107 - accuracy: 0.4300 - 5ms/epoch - 1ms/step
Epoch 11/150
4/4 - 0s - loss: 1.1022 - accuracy: 0.4200 - 5ms/epoch - 1ms/step
Epoch 12/150
4/4 - 0s - loss: 1.0951 - accuracy: 0.4200 - 4ms/epoch - 1ms/step
Epoch 13/150
4/4 - 0s - loss: 1.0879 - accuracy: 0.4200 - 

Epoch 103/150
4/4 - 0s - loss: 0.5824 - accuracy: 0.6500 - 3ms/epoch - 750us/step
Epoch 104/150
4/4 - 0s - loss: 0.5767 - accuracy: 0.6500 - 3ms/epoch - 718us/step
Epoch 105/150
4/4 - 0s - loss: 0.5715 - accuracy: 0.6500 - 3ms/epoch - 750us/step
Epoch 106/150
4/4 - 0s - loss: 0.5664 - accuracy: 0.6600 - 3ms/epoch - 750us/step
Epoch 107/150
4/4 - 0s - loss: 0.5614 - accuracy: 0.6700 - 3ms/epoch - 750us/step
Epoch 108/150
4/4 - 0s - loss: 0.5567 - accuracy: 0.6700 - 3ms/epoch - 750us/step
Epoch 109/150
4/4 - 0s - loss: 0.5523 - accuracy: 0.6600 - 3ms/epoch - 750us/step
Epoch 110/150
4/4 - 0s - loss: 0.5476 - accuracy: 0.6600 - 3ms/epoch - 750us/step
Epoch 111/150
4/4 - 0s - loss: 0.5433 - accuracy: 0.6700 - 4ms/epoch - 895us/step
Epoch 112/150
4/4 - 0s - loss: 0.5389 - accuracy: 0.6700 - 3ms/epoch - 750us/step
Epoch 113/150
4/4 - 0s - loss: 0.5346 - accuracy: 0.6700 - 2ms/epoch - 500us/step
Epoch 114/150
4/4 - 0s - loss: 0.5300 - accuracy: 0.6700 - 4ms/epoch - 975us/step
Epoch 115/150
4/

In [46]:
model.predict(scaled_X_test)

array([[4.0870607e-02, 5.4866773e-01, 4.1046172e-01],
       [9.4169462e-01, 5.2558094e-02, 5.7473192e-03],
       [7.7627157e-04, 2.4862178e-01, 7.5060195e-01],
       [4.0649779e-02, 5.0512141e-01, 4.5422882e-01],
       [1.5444349e-02, 5.0342155e-01, 4.8113415e-01],
       [9.1417241e-01, 7.5050794e-02, 1.0776767e-02],
       [1.7233303e-01, 5.4011136e-01, 2.8755566e-01],
       [4.0312354e-03, 3.1201351e-01, 6.8395525e-01],
       [1.1022886e-02, 4.0178764e-01, 5.8718944e-01],
       [8.4896132e-02, 5.6169176e-01, 3.5341209e-01],
       [1.2145241e-02, 3.9941007e-01, 5.8844471e-01],
       [9.2874956e-01, 6.1736166e-02, 9.5143542e-03],
       [9.4282728e-01, 5.1204477e-02, 5.9681982e-03],
       [9.3009824e-01, 6.0938355e-02, 8.9635216e-03],
       [9.7046518e-01, 2.6611466e-02, 2.9232865e-03],
       [5.4210633e-02, 5.3906751e-01, 4.0672192e-01],
       [3.5625857e-03, 2.8049445e-01, 7.1594298e-01],
       [7.9275392e-02, 5.5162567e-01, 3.6909890e-01],
       [5.9751347e-02, 5.269

In [48]:
np.argmax(model.predict(scaled_X_test), axis=-1)

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

###### Compare to y_test

In [50]:
predictions = np.argmax(model.predict(scaled_X_test), axis=-1)

In [51]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [53]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

In [54]:
confusion_matrix(y_test.argmax(axis=1),predictions)

array([[19,  0,  0],
       [ 0, 14,  1],
       [ 0,  0, 16]], dtype=int64)

In [59]:
print(classification_report(y_test.argmax(axis=1),predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.93      0.97        15
           2       0.94      1.00      0.97        16

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



In [60]:
accuracy_score(y_test.argmax(axis=1),predictions)

0.98

###### Save model for future use

In [65]:
model.save('basickerasmodel.h5')

###### Call saved model

In [62]:
from keras.models import load_model

In [64]:
new_model = load_model('basickerasmodel.h5')